export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_VERIFIED = 'USER_VARIFIED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';
export const CREATE_CHANNEL_REQUEST = 'CREATE_CHANNEL_REQUEST';
export const CREATE_CHANNEL_FAILED = 'CREATE_CHANNEL_FAILED';
export const GET_CHANNEL_DETAILS = 'GET_CHANNEL_DETAILS';
export const REQUEST_CHANNEL_DETAILS = 'REQUEST_CHANNEL_DETAILS';
export const CHANNEL_DETAILS_FAILURE = 'CHANNEL_DETAILS_FAILURE';

export const SET_POST_DETAILS = 'CLEAR_POST_DETAILS';
export const REQUEST_POST_DETAILS = 'REQUEST_POST_DETAILS';
export const CLEAR_POST_DETAILS = 'CLEAR_POST_DETAILS';
export const FULL_POST_DETAILS = 'FULL_POST_DETAILS';
export const REQUEST_COMMENT = 'REQUEST_COMMENT';
