export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_VERIFIED = 'USER_VARIFIED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_SIGNUP_LOAD = 'USER_SIGNUP_LOAD';
export const USER_SIGNIN_LOAD = 'USER_SIGNIN_LOAD';
export const USER_LOAD_END = 'USER_LOAD_END';

export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';
export const CREATE_CHANNEL_REQUEST = 'CREATE_CHANNEL_REQUEST';
export const CREATE_CHANNEL_FAILED = 'CREATE_CHANNEL_FAILED';
export const GET_CHANNEL_DETAILS = 'GET_CHANNEL_DETAILS';
export const REQUEST_CHANNEL_DETAILS = 'REQUEST_CHANNEL_DETAILS';
export const CHANNEL_DETAILS_FAILURE = 'CHANNEL_DETAILS_FAILURE';
export const REQUEST_ADDED_POSTS = 'REQUEST_ADDED_POSTS';
export const ADDED_POSTS_SUCCESS = 'ADDED_POSTS_SUCCESS';
export const ADDED_POSTS_FAILED = 'ADDED_POSTS_FAILED';
export const REQUEST_DELETE_POSTS = 'REQUEST_DELETE_POSTS';
export const DELETE_POSTS_SUCCESS = 'DELETE_POSTS_SUCCESS';
export const DELETE_POSTS_FAILED = 'DELETE_POSTS_FAILED';
export const FETCH_SELECTED_POST = 'FETCH_SELECTED_POST';
export const SET_SELECTED_POST = 'SET_SELECTED_POST';
export const SET_SELECTED_DRAFT = 'SET_SELECTED_DRAFT';
export const CLEAR_SELECTED_DRAFT = 'CLEAR_SELECTED_DRAFT';
export const SUCCESS_SELECTED_POST = 'SUCCESS_SELECTED_POST';
export const FAILED_SELECTED_POST = 'FAILED_SELECTED_POST';

export const SET_POST_DETAILS = 'CLEAR_POST_DETAILS';
export const REQUEST_POST_DETAILS = 'REQUEST_POST_DETAILS';
export const CLEAR_POST_DETAILS = 'CLEAR_POST_DETAILS';
export const FULL_POST_DETAILS = 'FULL_POST_DETAILS';
export const POST_DETAILS_FAILED = 'POST_DETAILS_FAILED';
export const UPDATE_LIKE = 'UPDATE_LIKE';
export const UPDATE_SAVE = 'UPDATE_SAVE';
export const REQUEST_COMMENT = 'REQUEST_COMMENT';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAILED = 'COMMENT_FAILED';
export const REQUEST_DELETE_COMMENT = 'REQUEST_DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED';

export const GET_SPONSOR_ADS = 'GET_SPONSOR_ADS';
export const SPONSOR_ADS_SUCCESS = 'SPONSOR_ADS_SUCCESS';
export const SPONSOR_ADS_FAILED = 'SPONSOR_ADS_FAILED';
export const SPONSOR_ADS_CANCELLED = 'SPONSOR_ADS_CANCELLED';
export const REQUEST_CREATE_AD = 'REQUEST_CREATE_AD';
export const CREATE_AD_SUCESS = 'CREATE_AD_SUCESS';


export const ADMIN_SIGNIN = 'ADMIN_SIGNIN';
export const ADMIN_VERIFIED = 'ADMIN_VERIFIED';
export const ADMIN_SIGNOUT = 'ADMIN_SIGNOUT';
